import Link from "next/link";
import Footer from "../footer";
import Navbar from "../navbar"
import Top from "../Top"

export default function ZakladniInformace() {
    return (
        <div className="">
              <Top/>
              <header>
                <Navbar/>
                <h1 className="lg:text-2xl text-xl p-4 pl-10 bg-gradient-to-l from-black via-yellow-900 to-yellow-700 text-white">ZÁKLADNÍ INFORMACE</h1>
              </header>
            <main className="bg-black min-h-screen bg-gradient-to-tl from-black via-black to-red-950 p-5">
              <link href="./output.css" rel="stylesheet"></link>
              <div className="text-left flex mx-auto justify-center max-w-6xl">
                <h2 className="text-2xl p-5 mt-10 text-white animate-fadeIn">Stručný přehled</h2>
              </div>
              <div className="flex max-w-6xl mx-auto text-xl text-pretty flex-col space-y-10">
                <p className="text-white animate-slideInLeft">Češi se v současné době vyskytují v Německu v počtu přibližně 50 000 jedinců. Jejich přistěhování mělo v minulosti politické a dnes převážně ekonomické důvody. Ve 20. století šlo často o politickou emigraci, kdy lidé nespokojení s režimem odcházeli nejen do Spojených států amerických či Kanady, ale také do západního Německa, kde hledali svobodu a bezpečí. V současnosti převládají ekonomické motivy. Češi míří do Německa za lepšími pracovními a studijními příležitostmi, vyšší životní úrovní a stabilnějším pracovním trhem. Někteří se rozhodují i z osobních důvodů – láká je určitá oblast, chtějí poznat jinou kulturu, nebo se nebojí vystoupit ze své komfortní zóny a osvojit si němčinu.</p>
                <p className="text-white animate-slideInLeft">Češi se nejvíce soutřeďují v Bavorsku a Sasku, kam se současné generace stěhují kvůli blízkosti hranic a kvůli pracovním příležitostem. Potomci českých rodičů na území Německa se taktéž velmi často nacházejí právě zde. Další lokací je například Hesensko, jelikož je to region s dobrou ekonomikou a láká hlavně kvalifikované odborníky. V neposlední řadě se Češi soutřeďují i do velkých měst, která lákají mimo jiné i studenty. Z hlediska profesí najdeme široké spektrum – od manuálních dělníků a zdravotnického personálu až po vysoce kvalifikované inženýry, výzkumníky nebo pracovníky v IT. Silně zastoupeni jsou i pendleři, kteří pracují v Německu, ale bydlí stále v Česku. Češi bývají v Německu vnímáni jako snadno integrovatelná menšina, kulturně i jazykově blízká. Přesto si uchovávají vlastní identitu prostřednictvím krajanských spolků, českých škol či kulturních center (např. České centrum v Berlíně). Pro druhou generaci je typická dvojjazyčnost, což posiluje jejich schopnost pohybovat se mezi dvěma kulturami. Za hlavní výzvy lze považovat udržení českého jazyka u dětí vyrůstajících v německém prostředí, vyšší životní náklady v některých regionech a složitější začlenění pendlerů, kteří sice pracují v Německu, ale zůstávají pevně vázáni na české zázemí.</p>
              </div>
              <div className="text-left flex mx-auto justify-center max-w-6xl">
                <h2 className="text-2xl p-5 mt-10 text-white animate-fadeIn">Z jakého důvodu by mohlo Čecha Německo zaujmout?</h2>
              </div>
              <div className="flex max-w-6xl mx-auto text-xl text-pretty flex-col space-y-10">
                <p className="text-white animate-slideInLeft">Důvody, proč se Češi rozhodují odejít do Německa, jsou velmi pestré. Zatímco v minulosti hrály roli hlavně politické okolnosti, dnes převažují faktory ekonomické, studijní a osobní. Přesto lze říci, že v jádru stojí především snaha o lepší životní podmínky a možnost osobního či profesního rozvoje.</p>
                <p className="text-white animate-slideInLeft">Ne všichni lidé se ovšem do Německa odstěhují, mnozí pouze jezdí přes hranice jen do Německa pracovat. Vyšší platy jsou pak to, co by člověka nutilo vystoupit ze své komfortní zóny, Německo nabízí ve srovnání s Českem vyšší průměrné mzdy, větší stabilitu pracovního trhu a širší nabídku pracovních pozic. Především v průmyslových centrech, jako je Mnichov (high-tech a IT), Stuttgart (automobilky), Frankfurt (finance) nebo Hamburk (logistika), nacházejí Češi dobré uplatnění. Z těchto důvodů  nemají lidé problém jít pracovat do jiného prostředí a možná se i základně naučit jazyk dané země. V případě Němčiny, jedná se tak celkem o výzvu, hlavně v pozdějším věku. Oproti například angličtině má němčina pády a obecně je na první pohled komplexnější. S angličtinou byste v Německu pravděpodobně přežili, ale znalost jazyka vám v prostředí, kde se možná rozhodnete žít, nepochybně prospěje. Kromě pracovního života je zde i aspekt studentského života. Německo vám může nabídnout i kvalitnější vzdělání, jako příklad si můžeme uvést Technickou univerzitu Mnichov. Ta zcela určitě láká mnohé technické nadšence z okolních zemí, jelikož její prestiž je poměrně velká a zároveň má i širší a hlubší záběr do mnohých problematik. Německo je domovem řady dalších prestižních univerzit, jako je Univerzita v Heidelbergu či RWTH Aachen. Významným lákadlem je skutečnost, že studium na veřejných vysokých školách je v mnoha spolkových zemích buď zcela bez školného, nebo finančně dostupné. To přitahuje české studenty, kteří zde často pokračují i v akademické kariéře.</p>
                <p className="text-white animate-slideInLeft">Jiným nemusí záležet čistě na ekonomických aspektech, v Německu žijí i Češi, jejichž důvody byly i mnohem prostší. Jak již bylo zmíněno, spousta lidí si zde našlo partnera a z různých důvodů se nakonec rozhodli zůstat v Německu. Existují samozřejmě i případy, kdy se děje přesně naopak. Důvody se liší osoba od osoby, ale většinou se tak stane, pokud je situace v Německu výhodnější, např. koupě bytu, domu, apod. I tento důvod je ale celkem logický a napadl by vás rychle. Jiní měli například důvod, že jsou lidé v Německu méně zamračení, obecně milejší. Zde je opět pravidlo (které ale nemusí nutně platit vždy), ža čím víc na jih se dostanete, tím více poznáte jinou atmosféru. Dáme si jeden příklad situace, která se opravdu stala:</p>
                <p className="text-gray-300 animate-slideInLeft italic max-w-3xl text-center mx-auto">Jak byste reagovali, kdybyste pracovali v poměrně drahé restauraci, a najednou vám spadla sklenička z podnosu, kterou jste právě odnesli ze stolu hosta? Asi byste byli naštvaní, přece jen asi dostanete lehce vynadáno a ještě to budete muset uklízet, a to hodně pečlivě, jelikož je restaurace pet-friendly a rozhodně nechcete, aby se vám po tomto incidentu ozval host, že má jeho pes zaražený střep v tlapce. Prostě samá negativa. Viděla jsem přesně takový scénář několikrát, a naštvání rozhodně bylo velmi časté. Ne ovšem v Bavorsku - tam číšník rozsekal skleničku, nahodil úsměvný výraz a po chvilce se začal své chybě smát. Kolemjdoucí servírka si toho všimla také a ačkoliv měla poloúsměv na tváři, ukázala na chlapíka výhružný prstík. Ten se místo studu a strachu co bude začal smát ještě víc. Pak si to samozřejmě šel uklidit, ale obecně zde panuje takový větší klid, nadhled, až skoro rozjívenost... </p>
                <p className="text-white animate-slideInLeft">Nelze zapomenout ani na přírodní prostředí a volnočasové aktivity. Německo nabízí rozmanitou krajinu – od Alp přes Schwarzwald až po pobřeží Severního a Baltského moře. Vyšší hory, rozsáhlé lesy a hustá síť cyklostezek či turistických tras lákají milovníky přírody a sportu. Najdou se i tací, kterým toto stačí jako důvod k odstěhování. Na druhé straně existují i výzvy, které je třeba zvážit. Jedná se zejména o odloučení od rodiny a známých, vyšší životní náklady v některých regionech a jazykovou bariéru. Celkově lze říci, že motivace k přesunu do Německa je komplexní – od ekonomických a studijních důvodů, přes rodinné vazby a kulturní lákadla až po prostý obdiv k přírodě. Každý jedinec má vlastní cestu a své priority, ale dohromady vytvářejí pestrý obraz důvodů, proč naše západní sousedství zůstává pro Čechy atraktivní volbou.</p>
              </div>
              <div className="text-left flex mx-auto justify-center max-w-6xl">
                <h2 className="text-2xl p-5 mt-10 text-white animate-fadeIn">Vyplatí se naučit jazyk?</h2>
              </div>
              <div className="flex max-w-6xl mx-auto text-xl text-pretty flex-col space-y-10">
                <p className="text-white animate-slideInLeft">Pokud se už někdo rozhodně v Německu žít, rozhodně není od věci se naučit i jazyk, jelikož to zcela nepochybně zjednuduší každodenní život. Zároveň to i otevře dveře zcela novému světu. Ti, kteří ovládají více jazyku, by dali této myšlence za pravdu. Vemte si to takhle - ve svém rodném jazyce konzumujeme obrovské množství různých informací. Lidi kolem nás si povídají v tramvaji, díváme se na zprávy, čteme články, nebo třeba projíždíme sociální sítě. Chodíme do restaurací, chodíme do školy. S každým naučeným jazykem se toto znásobí a máme možnost mít přístup k mnohem většímu množství informací (ne že by těch informací bylo málo, dnes jsme doslova přehlcení informacemi, ale jde o princip "poznávání světa podobně, jako malé dítě". Můžeme sledovat regionální zprávy. Můžeme si přečíst jídelní lístek a objednat si pohodlně jídlo, aniž bychom případné jazykové bariéry museli dohánět gestikulováním. Můžeme s lidmi vtipkovat v jejich rodné řeči. Člověku to vytváří i určitý hezký pocit, když ví, že mluví cizí řečí a je schopen jí rozumět a komunikovat v ní.</p>
                <p className="text-white animate-slideInLeft">Konkrétně v Německu je situace poměrně dobrá, ačkoliv záleží region od regionu. Lidé ocení, když se snažíte mluvit jejich rodnou řečí. Pokud ale uvidí, že máte spíše problémy, nabídnou angličtinu brzy sami. Žádné extra naštvání se taktéž nekoná, pokud vyslovíte něco špatně. Dokonce se občas setkáte i s tím, že se vás v restauraci zeptají, jak se nějaká základní fráze řekne po vašem, aby vám vaší snahu oplatili. Neplatí to tak u všech, ale jsou zde i jisté regionální rozdíly. Ve spolkových zemí bývalé NDR jsou reakce na snahu mluvit němčinou více neutrální. Zatímco naopak na jihu, hlavně Bavorsko, jsou reakce více procítěné. Není to však podmínkou. Dostat můžete i negativní reakci. Někteří Bavoři mají v sobě určitou tvrdohlavost, a můžou k vám naschvál promlouvat silným dialektem, pokud zaznamenají, že máte s němčinou problémy. Jsou to ovšem ojedinělé případy. Je taktéž otázkou, zda člověku bude stačit standardní spisovná  němčina. Jak by vám mnozí Češi v žijící v Německu pověděli, rozhodně se standardní němčinou domluvíte, ale musíte občas tajně doufat, že se s vámi rodilý mluvčí určitého dialektu nebude chtít s vámi nějak extra vybavovat. Problémem je, že některé dialekty jsou od standardní němčiny tak odlišné, že druhému pomalu nebudete rozumět ani slovo. Ne, že by situace v Česku byla jakkoliv jenoduchá též. Dialekty máme i zde a pro někoho, kdo se učí česky, by mohla i naše nářečí činit obrovské problémy. Někdy i pro rodilé mluvčí, ale pořád jsou nářečí hodně vzájemně srozumitelná. V případě němčiny také panuje porozumění ve většině případu, ale i rodilí mluvčí mohou mít obtíže.</p>
                <p className="text-white animate-slideInLeft">Závěrem lze říci, že naučení jazyka není rozhodně povinnost, ale váš život to udělá značně jednodušším. V německu je stále poměrně časté, že dostanete odpověď: "anglicky mluvím špatně, ale pokusím se". Obecně je ale znalost angličtiny na dobré úrovni a většina Čechů neměla velký problém si v Německu najít práci i bez znalosti jazyka. Zcela logicky vám ale znalost jazyka přinese více příležitostí a rozhodně půjde i hladce zapadnout do kolektivu. I se základní znalostí jazyka to může někdy být oříšek. Pokud ovládáte základní slovíčka a fráze, budete stále nervózní mluvit před rodilými mluvčími, protože si nebudete úplně jisti gramatikou či výslovností. Pokud se tak setkáte s vaším kolektivem například v práci na obědě, může se stát, že se budete chtít do konverzace zapojit, ale než si rozmyslíte, co chcete říct a jestli je to správně, tak se mezitím stočí téma jinam. Pokud tedy bude člověk žít v Německu dlouhodobě, jednoznačně se může stát, že se bude cítit vyčleněný z kolektivu. S trochou motivace a odhodlání se ale lze dostat na obstojnou úroveň a vzhledem k tomu, že v Německu je opravdu velký počet cizinců, ale více než pravděpodobné, že už teď bydlí v Německu obrovské masy lidí, kteří budou ovládat němčinu mnohem hůře, než vy.</p>
              </div>
              <div className="text-left flex mx-auto justify-center max-w-6xl">
                <h2 className="text-2xl p-5 mt-10 text-white animate-fadeIn">Životní podmínky a úroveň</h2>
              </div>
              <div className="flex max-w-6xl mx-auto text-xl text-pretty flex-col space-y-10">
                <p className="text-white animate-slideInLeft">Německo je dnes jednou z nejrozvinutějších zemí v Evropě a není pochyb o tom, že již dlouhá léta láká spoustu cizinců. Životní úroveň je zde velká a ve srovnání s ČR jsou zde znatelně vyšší platy. Tomu odpovídají i některé ceny, ovšem světe div se, některé komodity jsou drahé přibližně stejně, a přitom si je za německý plat budete moci dovolit za menší úsilí. Jedná se tak především o jídlo, kterého cena je s ČR hodně srovnatelná. Zkrátka si koupíte více i za stejnou cenu výrobků. Je ale sehnat práci v Německu jednoduché? Obecně lze říci, že to není vždy úplně nejjednodušší, ale práci si většinou seženete bez větších problémů. Jak mnozí Češi popisují, záleží na spoustě faktorů. Základními faktory jsou vzdělání, předešlá praxe, ale i znalost jazyka. V menších firmách nebudete mít takové štěstí, pokud jste přišli pouze s některými základními slovíčky. Ne, že by se v takových formách angličtina nepoužívala, ale rozhodně bude spíše na pozadí než na popředí a většina kolektivu kolem vás bude němčinu preferovat. Pokud se do naučení jazyka příliš neženete, je tak lepší se dívat na mezinárodní firmy, případně i takové malé firmy, které se o komunikaci v angličtině hodně opírají. Velký počet zaměstantných cizinců vám jednoznačně pomůže. Tento jev bude samozřejmě častější ve velkých mezinárodních firmách. Tak jako ostatně všude, firmy vás dokáží i bez jazyka ocenit tehdy, kdy jste kvalifikovaní v žádaném oboru. Nejlépe i s praxí. V tomto případě pak jde o vaši kvalitu a forma nebude tolik řešit, zda dokážete hovořit plynně. Jako vždy, je to výhodou, ale kvalifikace, vzdělání a praxe vám v úspěchu půjdou hodně naproti. Pro ale lepší postup v práci a případné povýšení byste ale měli lepší znalost němčiny zvážit. Vaši jistou výhodou je i rodný jazyk, mnohé firmy by mohly vaši dokonalou znalost češtiny, případně i slovenštiny ocenit. </p>
                <p className="text-white animate-slideInLeft">Život v Německu jsme doposud malovali celkem lákavě, že se lidem zde žije jako v peřince. Není to však úplně pravda a nelze říci, že by nutně byl život v Německu "jednodušší". Bydlení je stejně jako u nás drahé, a to hlavně ve větších městech, kde může být opravdu těžké sehnat rozumně naceněné bydlení. A tady vám tentokrát německý plat nepomůže. Kde vám ale rozhodně může pomoci, jsou lokace s menšími městy či venkov obecně. Tam už je situace pochopitelně mírnější a snadnější na sehnání bydlení. Stejně jako ostatně kdekoliv, musíte ale čelit očividným nevýhodám venkova - špatná dostupnost obchodů, pracovních a studijních příležitostí, a tak dále.</p>
              </div>
              <div className="text-left flex mx-auto justify-center max-w-6xl">
                <h2 className="text-2xl p-5 mt-10 text-white animate-fadeIn">Asimilace a možná kulturní šoky?</h2>
              </div>
              <div className="flex max-w-6xl mx-auto text-xl text-pretty flex-col space-y-10">
                <p className="text-white animate-slideInLeft">Nyní se podíváme, jak se Češi zžili s německou kulturou a s některými odlišnostmi. Zde je nutno upozornit, že tyto zkušenosti jsou dosti subjektivní a mohou se lišit jak region od regionu, tak i člověk od člověka. Shrneme si co nejvíce pohledů, případně i těch protichůdných. Vzhledem k tomu, že Německo je náš soused a dlouhá léta zde měli Němci i velký vliv, nelze očekávávat, že by kultura v Německu byla nějak propastně odlišná. Stavby jsou podobné těm našim. Zvyky jsou také téměř totožné. Způsob života velmi podobný též. Po příjezdu do Německa žádný extra šok nedostane asi nikdo. Jsou zde ovšem malé odchylky, kterých si začnete všímat třeba až po čase. Tak třeba obchody. Chcete si koupit párek a rohlík v neděli na večeři? Tak to máte smůlu, jelikož žádný obchod v tu dobu otevřený nebude. Dokonce máte občas smůlu i v pondělí a úterý, kde si odpoledne chcete dát něco k pozdnímu obědu, a taktéž nebudete mít štěstí všude, jelikož jsou některé restaurace zavřené. Uvidíte na jejich dvěřích často jen ceduli: "Ruhetag", což znamená doslova "den klidu". Nestálé otevírací doby a časté volno tak může být pro Čecha nezvyklé a nemusí s tím počítat. Češi, co v Německu žijí už delší dobu, toto často zmiňují jako věc, která jim na Německu vadí. Dalším častým negativem není přímo Německo jako takové, jako spíš velký přísun cizinců a obecně zhoršení bezpečnosti. Konkrétní případ zažil i jeden Čech žijicí v Německu již dlouhou řadu let, kdy si celá léta nechával své kolo venku, nezamčené. Stalo se tak až po uprchlické krizi, kdy mu bylo jeho vždy odemčené kolo odcizeno. V souvislosti s koly je i toto určitý kulturní rozdíl, ale málokoho by v ČR napadlo si nechat své kolo venku odemčené, o to víc ne ve velkých městech, na vesnicích ještě občas na někoho s volně přístupným kolem narazíte. Řekli byste si, že takový člověk si přímo říká o jeho odcizení. Zamknout kolo je základ. Ne ovšem v Německu, kde bylo vždy k vidění spousta kol u domů, přičemž ani jedno nebylo zamčeno. Dále si Češi stěžují i na daně, či regulace, které často nazývají přehnanými.</p>
                <p className="text-white animate-slideInLeft">Co se ale týče asimilace, většinou zde nebývá mnoho problémů. Češi popisují Němce jako často milejší a usměvavější, ačkoliv někteří stále vnímají ČR jako zemi, která je nějakým způsobem "pozadu" a je méně rozvinutá. Vysloveně urážení národnosti je ale spíše vzácnost. Pokud nějaké předsudky jsou, většinou si je nechávají lidé pro sebe. Jak již ale bylo zmíněno, většina Čechů má dobré zkušenosti se zapadnutím do kolektivu. Resp. se zapadnutím do celkové společnosti. O to víc, pokud se snažíte i naučit jazyk. Narozdíl od zdejších není v Německu časté, že byste dostali posměch za špatnou úroveň jazyka, a to hlavně za výslovnost. Je to způsobené i velkým počtem cizinců, tudíž není třeba se za svoji němčinu zas tolik stydět, snaha je vždy vítána a ve většině případu nebude hrozit výsměch či jiné projevy na vaši mluvu.</p>
              </div>
              <div className="text-left flex mx-auto justify-center max-w-6xl">
                <h2 className="text-2xl p-5 mt-10 text-white animate-fadeIn">Češi jako taková alochtonní menšina</h2>
              </div>
              <div className="flex max-w-6xl mx-auto text-xl text-pretty flex-col space-y-10 lg:pb-32">
                <p className="text-white animate-slideInLeft">Ačkoliv jsme historicky měli s Německem společné mnohé (a ostatně i s Rakouskem), tak přesto se nestalo, že by v Německu byla jakkoliv menšina Čechů zakořeněna na tomto území. Pro jednoduchost se omezíme na modernější doby - vlny Čechů sem přiházely v 19. století, velká vlna pak přišla v půlce dvacátého století, kdy spousta lidí emigrovala, ačkoliv hlavně z politických důvodů. Nedá se tedy mluvit o nějak zvlášť historické české menšině. I v současné době jsou Češi v Německu často první generací, která se přestěhovala. Pokud první generací není, je poměrně časté, že se upřednostňuje země pobytu, tudíž ztrácí tyto děti spojení s českou kulturou a i jazykem. Pro některé už je to jenom jistá zajímavost, že mají svůj původ v Čechách. Je to ovšem velmi subjektivní. Mnozí mají stále dvojjazyčnou domácnost kvůli tomu, že je zbytek rodiny v Čechách a tudíž se jazyk nevytrácí. Schopnosti lidí, co jsou sice potomky Čechů, ale bydlí dlouhodobě v Německu, jsou poněkud limitované, co se českého jazyka týče. Většinou zvládají základní fráze, ale složitějším už mají problém porozumět. Dokonce se i pohledy na tyto dva národy mohou lišit. Zatímco v předešlých kapitolách jsme nakousli fakt toho, že vám první generace přistěhovalých čechů řekne, že jsou Němci obecně milejší a usměvavější, od generace druhé se taky můžete úplný opak. Tak jak pravila jedna z respondentek:</p>
                <p className="text-gray-300 animate-slideInLeft italic max-w-3xl text-center mx-auto">... und ich muss sagen das alle Tschechen hübscher sind als typische hässliche Deustche.</p>
                <p className="text-gray-300 animate-slideInLeft italic max-w-3xl text-center mx-auto">... a musím říct, že všichni Češi jsou milejší než typičtí oškliví Němci</p>
                <p className="text-white animate-slideInLeft">Je to tak určitý paradox, ačkoliv samozřejmě jde především o zkušenosti a lidí je na světě opravdu mnoho a mnohdy nezáleží na jejich původu a v každém koutě světa najdete hodné, usměvavé lidi, a na úplně stejném místě najdete i hromadu bručounů. Je to celé o temperamentu. Možná i o výchově. Je to ovšem hezký kontrast, že věci nemusí být tak, jak se na první pohled zdají. Může to být zapříčiněno i tím, že se jinak lidé chovají na veřejnosti a jinak v soukromí. Obecně se lidé snaží alespoň trochu přetvářet a chovat se mile, i když jsou vnitřně zrovna ve špatné náladě. Pro Čechy je ovšem charakteristické, že velkou snahu své pocity zahalit nemají. Pokud má někdo špatný den, dá vám to najevo. Samozřejmě jako vždycky, neplatí to univerzálně.</p>
                <p className="text-white animate-slideInLeft">Pokud si Čechy v Německu shrneme, není to úplně zakořeněná menšina a opravdu velký počet současných Čechů jsou první přistěhovalou generací. Je tak možné, že do budoucna se komunita rozšíří a budeme svědky něčeho jako v USA, kde můžeme narazit na opravdu shromážděné komunity. V Německu jsou Češi spíše rozptýlení, jedinými ucelenějšími komunitami jsou ty v Sasku a v Bavorsku, ale ani tam nemáte vyloženě nějaká místa, kde každý bude mluvit česky. Pokud takové místo je, jedná se tak především o spolky a české školy. Potřebu českých škol vnímají první generace Čechů, kteří si všímají, že jejich děti ztrácí kontakt s češtinou a českou kulturou obecně. Je to tedy snaha, jak na svůj původ nezapomenout. Přesto se ale často děje, že tyto děti nakonec mluví lépe neměcky a češtinou jen lámaně. Jsou ovšem jedinci, co se stále identifikují jako Češi, i přesto, že by se s rodilým mluvčím nedomluvili na 100% a rozhodně jim šlo špatně vtipkovat kvůli malé slovní zásobě. Současné první generace se většinou sice učí němčinu, ale již to není vnímáno jako naprostá povinnost, což umožňuje podmínky pro vzrůst čistě česky hovořících komunit. Příval Čechů se každým rokem zvětšuje, ostatně jak je i vidět v datech obsažených v Interaktivní mapě. Nejsou tak samozřejmě jedinou národností, v současné době je v Německu opravdu vělký počet cizinců. Tudíž se dá do bodoucna očekávat, že v Německu vzroste půda pro nové alochtonní menšiny, Čechů včetně. </p>
              </div>
              <div className="text-left flex mx-auto justify-center max-w-6xl">
                <h2 className="text-2xl p-5 mt-10 text-white animate-fadeIn">Češi v Německu v jiných zdrojích</h2>
              </div>
              <div className="flex max-w-6xl mx-auto text-xl text-pretty flex-col space-y-10 lg:pb-32">
                <p className="text-white animate-slideInLeft">Stránka Jak do Německa obsahuje cenné informace pro život v Německu, jako jsou obecné informace o povinnostech občana, výpis svátků, různé tipy, včetně učení se jazyka a mimo jiné i rozhovory s Čechy žijících v Německu:</p>
                <Link href="https://jakdonemecka.cz/" className="text-yellow-400 hover:text-yellow-200">Jak do Německa</Link>
                <p className="text-white animate-slideInLeft">Pro odlehčení a zábavu existuje YouTube kanál, který se touto problematikou zabývá, ale spíše z hlediska zábavy než čistě edukativního obsahu. </p>
                <Link href="https://www.youtube.com/@CesivNemecku/" className="text-yellow-400 hover:text-yellow-200">YouTube - Češi v Německu</Link>
                <p className="text-white animate-slideInLeft">Pro aktivní konverzování a nejnovější informace od Čechů a Slováků v Německu slouží skupina na Facebooku Češi a Slováci v Německu, kde kromě tazatelů a současně na území Německa žijicích Čechů a Slováků zvěřejňují příspěvky i české a slovenské spolky</p>
                <Link href="https://www.facebook.com/groups/475729449183717/" className="text-yellow-400 hover:text-yellow-200">Češi a Slováci v Německu</Link>
              </div>
            </main>
            <Footer />
        </div>
    );
}